### ISSUE TITLE
Popover goes beyond viewport boundaries when container is using flex

### ISSUE THREAD

**Issue by JanuaryLimes** [atomiks/tippy.js-react#105]
I made a little demo to ilustrate my findings: 

https://codesandbox.io/s/awesome-sutherland-m8wbw 

is it a  bug or am I doing something wrong?

PS great library I'm loving using it :wink:

**Comment by atomiks** [comment]
Maybe it's a Popper.js issue. Can you reproduce using it? https://codepen.io/FezVrasta/pen/wGqJEz

**Comment by atomiks** [comment]
This prop in particular:

```jsx
<Tippy appendTo="parent" />
```

appends it to the flex container. If you remove it, it is positioned correctly (popper is appended to the `<body>` instead). But then it's not accessible since it's not directly after the reference element (button) in the DOM source order.

So you could either:

- Find the next nearest parent where tabbing order is still correct, but outside of the container
- Use a ref and programmatic `.focus()` to create accessible modal-like behavior even when it's appended to the `<body>`

**Comment by JanuaryLimes** [comment]
Thanks! I think your suggestions will be enough for me

**Comment by julesbou** [comment]
I had the same problem, the content is jumping as I scroll, I fixed it by using: 
```
<Tippy appendTo={documentBody} />
```
(happily this tooltip wasn't needed to be acessible)
