### ISSUE TITLE
`useSingleton` is not memoization safe

### ISSUE THREAD

**Issue by grossbart** [atomiks/tippy.js-react#146]
In the `useSingleton` hook you return a new function on every call. This is not ideal, as it means that the return value can't be passed around safely, e.g. to a memoized component or another hook's dependency array.

What happened in my case was that the memoization didn't work anymore because reference equality of the function was broken. This led to a lot of unnecessary re-renders.

https://github.com/atomiks/tippy.js-react/blob/8ec5fd9775e18f002a5b525c8bb254dafaa1daa4/src/hooks.js#L32

**Comment by atomiks** [comment]
Makes sense, do you want to make a PR to fix?

**Comment by atomiks** [comment]
Is this a safe fix?

```js
// Above
const deps = [component.instances.length];

return useCallback(instance => {
  component.instances.push(instance);
}, deps);
```

**Comment by atomiks** [comment]
I guess this isn't a big deal. No upvotes or comments since the issue was made 🤷‍♂

**Comment by sanjevirau** [comment]
Hi @grossbart @atomiks , I faced the error `Uncaught RangeError: Maximum call stack size exceeded` due to this issue. I have a use-case where the page will keep rendering for every 2-3 seconds. Thus, the `useSingleton` keep rerendering causing an error on `createSingleton` for the maximum call. 

Can the hook `useSingleton` memotized?

**Comment by IanVS** [comment]
I'm also seeing buggy behavior when trying to pass the `target` from `useSingleton` into a memoized `columns` definition from react-table.  I'm seeing position jumps, and other odd behavior, and I wonder if it's because of this issue, perhaps.
