### ISSUE TITLE
placement broken in v3

### ISSUE THREAD

**Issue by eugenenelou** [atomiks/tippy.js-react#157]
Hello,
I tried to upgrade to v3 and it looks like the placement of tooltips is broken. They either overflow the window or are shrunk to fit in the window. I have no problem in v2. 

Can this be due to tippy.js v5?

**Comment by atomiks** [comment]
Have you got a CodeSandbox repro? First time I've seen this problem reported in the new version

**Comment by Kilian** [comment]
I have the same issue, but only when using the singleton. When switching to a much longer tooltip text in the same singleton, the tooltip will be out of bounds if close to the window border. When starting with the long tooltip, it will be positioned correctly. This also happens with flipOnUpdate set to true.

**Comment by Kilian** [comment]
Codesandbox: https://codesandbox.io/s/focused-bouman-e8oj6

1. Hover over the "long" button, see the tooltip correctly position in relation to the right window border
2. Move mouse to the "short" button, see the tooltip move to the correct position for the short button
3. Move mouse back to the "long" button, now see that the tooltip spills over the bounds on the right.

**Comment by atomiks** [comment]
@Kilian looks like it's due to the update transition. The window is getting stretched by the popper's dimensions but the position gets transitioned, causing the issue.

This fixes it: https://codesandbox.io/s/nice-sunset-cgziv

Create a positioned container with `overflow-x: hidden` and append the tippy to it.

I think singleton tippies would need their dimensions to transition as well to not need to do that. That's something I've been working on which makes singleton transitions look far better anyway, so I'd have to verify if it fixes it.

**Comment by Kilian** [comment]
Ah, using appendTo to move it to something other than body fixes it. My document.body was already positioned and had overflow though, so it's strange that it doesn't work there.

Will keep an eye out for the updated singleton! :)

**Comment by atomiks** [comment]
Another solution is to use `boundary="viewport"` without needing to alter your DOM context. That type of boundary sometimes may not be suitable though, but it's another alternative

**Comment by eugenenelou** [comment]
Hello, sorry for the delay.
I have not yet been able to fully reproduce my problem out of my app. It basically is the same problem as Kilian but without even using the singleton. 

It may be due to my tooltip css, for example when adding just some padding to the tooltip, the placement is broken: https://codesandbox.io/s/old-violet-h76co.

Also @atomiks in your sandbox with `overflow-x: hidden` the problem is not fixed for me (I am using firefox)

**Comment by atomiks** [comment]
I accidentally saved over it without `appendTo="parent"` while doing later experiments lol woops. Works in FF/Chrome now.

@eugenenelou that's due to the height of the scrolling parent. If you set it to `200px` it's fine. I am guessing that's not your problem though.

**Comment by eugenenelou** [comment]
Ok that makes more sense 😄.

I am using the `interactive: true` yes, but appending to the body does not change anything. I still cannot reproduce the problem out of my app, and am starting to believe it's related to how the layout is handled.

I will continue investigating this and will update you if I can reproduce it.

**Comment by atomiks** [comment]
Going to close this, here are likely problems and the solutions:

## Interactivity

It's very likely be due to the node the tippy gets appended to when using interactivity (the parent node). Popper v1's positioning logic is not perfect when it comes to certain DOM contexts:

```js
appendTo={document.body}
```

with focus management necessary for accessibility

## Singleton

If using a transition, ensure you add:

```js
boundary="viewport"
```

or append to a clipping container that prevents the window from being stretched.

## Follow Cursor

When using variation placements (`-start` or `-end`), the variations got reversed in the latest version so they are actually correct now. If migrating from v2, use the opposite variation.
