### ISSUE TITLE
placement reversed in v3

### ISSUE THREAD

**Issue by mattleonowicz** [atomiks/tippy.js-react#159]
Hi,

In `3.1.1` Seems like placement is reversed somewhat. `placement="right-start"` behaves like `right-end` and I can see that confirmed by looking at `x-placement` attribute assigned to `.tippy-popper`, which is indeed set to `right-end` instead of `right-start`.

Or maybe its `tippy.js` fault? It's on `5.1.3` in my scenario.

EDIT: `followCursor` is interfering with this as well. In some other place I have Tippy with placement set to `left-end`, which becomes `right-end`, and after adding `folowCursor` it becomes `right-start`.

**Comment by atomiks** [comment]
`followCursor` reverses the variation due to an internal fix for a Popper.js problem – the "cursor reference" is given some virtual size, but the way this is implemented requires us to reverse the variation for the placement to appear correct relative to the cursor.

Do you have a CodeSandbox demonstrating the problem?

**Comment by atomiks** [comment]
Here is a demo: https://codesandbox.io/s/infallible-johnson-9545m

`followCursor` normalizes the placement into `right-end` when you specify `right-start` so that the cursor appears at the start of the tooltip. This is due to the fix mentioned earlier – in the previous version, when using `followCursor`, the variation placement was the reverse of what it is now (which was incorrect/unexpected behavior). 

Since it appears to stay normalized when flipping, so it doesn't look like there is a bug.

So in essence for v3, if you were specifying `-start` in v2, you now specify `-end` (and vice-versa). If you are new to the library, the placements now work as expected.
