### ISSUE TITLE
Tippy not playing well with styled component and redux

### ISSUE THREAD

**Issue by Cyrus-d** [atomiks/tippy.js-react#41]
I have styled component wrapped with tippy in a component. the component is connected to the redux store to dispatch/receive props.

everything works fine until store state change and causing rerender. after that, the popover won't show.

I have created codesandbox to demonstrate the problem:

[https://codesandbox.io/s/5w394qqzlk](https://codesandbox.io/s/5w394qqzlk)

Please look in 'Component.jsx' and follow instructions.

Thanks,

**Comment by KubaJastrz** [comment]
It's because you are creating a `Button` styled component in the `render` lifecycle method. Never a good idea. Most likely tippy creates event listeners to the "original" button component and it gets lost during the next re-render issued by store change.

Just move the `Button` component outside of your `Component`.

**Comment by Cyrus-d** [comment]
Thank you for the clarification, I tried your solution and it works fine.
