### ISSUE TITLE
Throw `useLayoutEffect` warning in version 2.1.0

### ISSUE THREAD

**Issue by RoberMac** [atomiks/tippy.js-react#58]
As title, this warning throw when server-side rendering

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.
```

**Comment by atomiks** [comment]
So that test was trying to tell me something too 😆 , I need to stop removing tests. Completely forgot about SSR for some reason.

`useLayoutEffect` is equivalent to `componentDidUpdate` and is what we want because we're mutating DOM elements...

https://github.com/facebook/react/pull/14596/files

Unfortunately, this link doesn't lead anywhere at the moment

I don't think this warning should even exist actually

**Comment by atomiks** [comment]
In the meantime while the warning exists, I think we can do this conditionally without breaking the rules of hooks:

```js
const useIsomorphicLayoutEffect = isBrowser ? useLayoutEffect : useEffect
```

At build time / on the server, it'll `useEffect` which is a no-op anyway. On the client, it'll do what we want (synchronous mutations).
