### ISSUE TITLE
Tooltip jumps when trigger='manual' and hideOnClick=false

### ISSUE THREAD

**Issue by Lazyuki** [atomiks/tippy.js-react#67]
https://codesandbox.io/s/nn7km3wrl

Tooltip fading in is fine but when it's fading out, it jumps first and then fades away.

**Comment by atomiks** [comment]
Interesting bug. In the meantime, you can achieve the same behavior without using state using these props:

```jsx
<Tippy
  content="Tooltip"
  placement="right"
  hideOnClick="toggle"
  trigger="click"
>
  <button />
</Tippy>
```

**Comment by Arkellys** [comment]
Removing the `placement` parameter seems to fix the problem. 🤔

**Comment by atomiks** [comment]
So I investigated this.

It doesn't show up in the vanilla lib: https://codepen.io/anon/pen/OqBXbr?editors=1010

But it has to do with the `.tippy-notransition` class that gets added to the tooltip once `onShown()` is complete. If you write in your CSS:

```css
.tippy-notransition {
  transition: unset;
}
```

The problem goes away. This class is only relevant if you're using `flipOnUpdate: true` (which is false by default), which removes undesirable transitions when the tooltip flips to a new placement (due to different `transform`s on the tooltip node). 

Likely a scheduling problem or something, maybe? Possibly can change the internal implementation to fix transitions. Maybe don't use a class and debounce disabling transitions `onUpdate`.

**Comment by Lazyuki** [comment]
Interestingly enough, removing the `placement` parameter fixes the problem as long as you don't add other position related parameters, like `distance`, `flip`, `flipOnUpdate`, `arrow` etc. And it doesn't matter if you set them to true or false or whatever the default is. Having those parameters as props alone causes the jump again.

**Comment by atomiks** [comment]
@Lazyuki 

Something to do with destroying the popperInstance and recreating it then?

```js
instanceRef.current.set(options)
```

Removing this line in the React wrapper also fixes it, and it's showing up in the vanilla lib when updating a popperInstance dependency: https://codepen.io/anon/pen/OqBXbr?editors=1010
