### ISSUE TITLE
Classname prop for arrow

### ISSUE THREAD

**Issue by mklopets** [atomiks/tippy.js-react#84]
The current `className` prop only allows for partial styling of the tooltip – would be great to also have an optional `arrowClassName` prop to use instead of resorting to targeting global hardcoded classnames.

**Comment by atomiks** [comment]
There would need to be a className for every different node in `instance.popperChildren` for consistency (`backdrop` as well). 

So while you do currently target `.yourClassName .tippy-arrow` as a descendant, it doesn't cause conflicts, so I don't believe this is really necessary?

**Comment by mklopets** [comment]
Sure, I didn't consider the need for other classes, to be honest. But I actually think being able to specify all of those would be super nice. Not a blocker for using the lib tho, so feel free to close. Thanks for your work!

**Comment by atomiks** [comment]
For anyone wondering how to do this declaratively: proxy/wrapper components solve everything! You get access to all of the tippy's elements so you can do anything you want to them with an effect hook. You can also do this to add event listeners declaratively to the tippy elements, etc etc.

```jsx
function TippyExtended({arrowClassName, ...props}) {
  const instanceRef = useRef();

  function onCreate(instance) {
    if (props.onCreate) {
      props.onCreate(instance);
    }

    instanceRef.current = instance;
  }

  // Need to account for multiple classes though
  useLayoutEffect(() => {
    const {tooltip} = instanceRef.current.popperChildren;
    tooltip.classList.add(arrowClassName);

    return () => {
      tooltip.classList.remove(arrowClassName);
    };
  }, [arrowClassName]);

  return <Tippy {...props} onCreate={onCreate} />;
}
```

To keep this wrapper as lightweight as possible, I won't be adding these since it isn't a true blocker, and you can extend the component if necessary.
